name: rmms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0  
  google_fonts: ^6.2.1
  flutter_slidable: ^4.0.0
  gsheets: ^0.5.0
  flutter_bloc:
  connectivity_plus: ^6.1.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: fonts/Ubuntu-Bold.ttf
  #       - asset: fonts/Ubuntu-Light.ttf
  #       - asset: fonts/Ubuntu-Regular.ttf

